[package]
name = "lnp2p"
version = "0.3.0"
license = "MIT"
authors = ["Dr Maxim Orlovsky <orlovsky@pandoracore.com>"]
description = "LN P2P Library: rust implementation of lightning network peer protocol (BOLT-1, 2, 7, 9)"
repository = "https://github.com/LNP-BP/lnp-core"
homepage = "https://lnp-bp.org"
keywords = ["bitcoin", "lightning", "rgb", "smart-contracts", "lnp-bp"]
categories = ["cryptography::cryptocurrencies", "network-programming"]
readme = "README.md"
edition = "2018"

[lib]
name = "lnp2p"
path = "src/lib.rs"
crate-type = ["rlib", "staticlib"]

[dependencies]
amplify = { version = "3", features = ["stringly_conversions"] }
amplify_derive = "2.4.3"
lnpbp = "0.3"
rgb-core = { version = "0.3", optional = true }
strict_encoding = "1"
descriptor-wallet = { version = "0.3.3", features = ["keygen"] }
bitcoin = { version = "0.26", features = ["rand"] }
internet2 = { git = "https://github.com/zkao/rust-internet2", branch = "removeCreateUnmarshaller", features = ["bitcoin-ext", "lnpbp"] }
# internet2 = { path = "../rust-internet2", features = ["bitcoin-ext", "lnpbp"]  }
# internet2 = { version = "0.3.6", features = ["bitcoin-ext", "lnpbp"] }
serde_crate = { package = "serde", version = "1.0", features = ["derive"], optional = true }
serde_with = { version = "1.5", features = ["hex"], optional = true }
lazy_static = "1.4"

[features]
default = []
all = ["rgb", "serde"]
rgb = ["rgb-core", "internet2/rgb"]
serde = ["serde_crate", "serde_with", "amplify/serde", "bitcoin/use-serde"]
